<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>EchelonFoundry.Arca</PackageId>
    <AssemblyName>Arca</AssemblyName>
    <RootNamespace>Arca</RootNamespace>
    <Description>Arca (Echelon Foundry).</Description>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Library.fs" />
  </ItemGroup>
</Project>
